// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvvendhofyblpcyprlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdnZlbmRob2Z5YmxwY3lwcmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTk2ODYsImV4cCI6MjA2NjkzNTY4Nn0.qDP52iD96owykumHuNrJ0z9fM4ELYNqh-Lv9S0I-ZUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});